export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAIL = 'GET_PRODUCTS_BY_CATEGORY_FAIL';

export const FILTER_PRODUCT_REQUEST = 'FILTER_PRODUCT_REQUEST';
export const FILTER_PRODUCT_SUCCESS = 'FILTER_PRODUCT_SUCCESS';
export const FILTER_PRODUCT_FAIL = 'FILTER_PRODUCT_FAIL';